apiVersion: v1
kind: Service
metadata:
  name: {{ include "tom-demo.fullname" . }}
  labels:
{{ include "tom-demo.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "tom-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "backend"
